version: "3"
services:
  simpleapp:
    image: zjokinen/simpleapp
    container_name: simpleapp
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --interval 30
